import React, { useState, useEffect } from 'react';
import axios from 'axios';
import PharmacyHeader from '../PharmacyHeader/PharmacyHeader';
import PharmacyFooter from '../PharmacyFooter/PharmacyFooter';
import HistoryDetailsModal from './HistoryDetailsModal';
import './PharmacyHistory.css';

const PharmacyHistory = () => {
    const [history, setHistory] = useState([]);
    const [loading, setLoading] = useState(true);
    const [searchTerm, setSearchTerm] = useState('');
    const [selectedBillId, setSelectedBillId] = useState(null);
    const [isModalOpen, setIsModalOpen] = useState(false);

    const pharmacyLoginId = localStorage.getItem("loginId");

    const fetchHistory = async () => {
        try {
            setLoading(true);
            const response = await axios.get('http://127.0.0.1:8000/pharmacy/get_billing_history/', {
                params: { pharmacy_login_id: pharmacyLoginId }
            });
            setHistory(response.data.history || []);
        } catch (error) {
            console.error("Error fetching billing history:", error);
        } finally {
            setLoading(false);
        }
    };

    useEffect(() => {
        if (pharmacyLoginId) {
            fetchHistory();
        }
    }, [pharmacyLoginId]);

    const handleViewDetails = (billId) => {
        setSelectedBillId(billId);
        setIsModalOpen(true);
    };

    const filteredHistory = history.filter(item =>
        item.patient_name.toLowerCase().includes(searchTerm.toLowerCase()) ||
        item.doctor_name.toLowerCase().includes(searchTerm.toLowerCase())
    );

    return (
        <div className="pharmacy-history-page">
            <PharmacyHeader />
            <main className="history-main">
                <div className="container mt-50 mb-50">
                    <div className="page-header mb-30 d-flex justify-content-between align-items-center">
                        <div>
                            <h2>Pharmacy Billing History</h2>
                            <p>Track all medication bills generated by your pharmacy.</p>
                        </div>
                        <button className="btn ss-btn refresh-btn" onClick={fetchHistory}>
                            <i className="fas fa-sync-alt"></i> Refresh
                        </button>
                    </div>

                    <div className="table-controls mb-30">
                        <div className="search-container">
                            <input
                                type="text"
                                placeholder="Search by patient or doctor..."
                                value={searchTerm}
                                onChange={(e) => setSearchTerm(e.target.value)}
                                className="search-input"
                            />
                            <i className="fas fa-search search-icon"></i>
                        </div>
                    </div>

                    <div className="history-table-container shadow-sm rounded">
                        <table className="table history-table">
                            <thead>
                                <tr>
                                    <th>Patient Name</th>
                                    <th>Prescribing Doctor</th>
                                    <th>Billing Date</th>
                                    <th>Billing Time</th>
                                    <th>Total Amount</th>
                                    <th>Status</th>
                                    <th className="text-center">Actions</th>
                                </tr>
                            </thead>
                            <tbody>
                                {loading ? (
                                    <tr>
                                        <td colSpan="7" className="text-center py-5">
                                            <div className="spinner-border text-primary" role="status"></div>
                                            <p className="mt-2">Loading history...</p>
                                        </td>
                                    </tr>
                                ) : filteredHistory.length > 0 ? (
                                    filteredHistory.map((item) => (
                                        <tr key={item.bill_id}>
                                            <td><strong>{item.patient_name}</strong></td>
                                            <td>Dr. {item.doctor_name}</td>
                                            <td>{item.billing_date}</td>
                                            <td>{item.billing_time}</td>
                                            <td className="font-weight-bold text-primary">₹{item.total_amount.toFixed(2)}</td>
                                            <td>
                                                <span className={`status-badge ${item.status}`}>
                                                    {item.status}
                                                </span>
                                            </td>
                                            <td className="text-center">
                                                <button
                                                    className="btn btn-sm btn-outline-primary rounded-pill"
                                                    onClick={() => handleViewDetails(item.bill_id)}
                                                    title="View Full Details"
                                                >
                                                    <i className="fas fa-eye mr-1"></i> View
                                                </button>
                                            </td>
                                        </tr>
                                    ))
                                ) : (
                                    <tr>
                                        <td colSpan="7" className="text-center py-5">
                                            <i className="fas fa-history fa-3x text-muted mb-3"></i>
                                            <p>No billing records found.</p>
                                        </td>
                                    </tr>
                                )}
                            </tbody>
                        </table>
                    </div>
                </div>
            </main>

            <HistoryDetailsModal
                isOpen={isModalOpen}
                onClose={() => setIsModalOpen(false)}
                billId={selectedBillId}
            />

            <PharmacyFooter />
        </div>
    );
};

export default PharmacyHistory;
